### PR TITLE
7.1.4: HTSP connection related fixes and cleanup

### LINKED ISSUE #465: frequent UI freeze on LibreELEC / OSMC
I get very frequent UI freezes when the Tvheadend plugin loads the available channels and records in the overview on LibreELEC and OSMC on a Raspberry Pi 1. I can still login via ssh etc. but the Kodi UI becomes completely frozen at 100% CPU usage.

Since I can still login via ssh and this happens before playing any live stream, I think that this issue is different from https://github.com/kodi-pvr/pvr.hts/issues/307.

I get a couple of errors:
```
ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command getDiskSpace failed: No response received
ERROR: GetDriveSpace: Add-on 'Tvheadend:omv.local:9982' returned an error: server error
ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to read packet (Bad file descriptor)
ERROR: GetTimers: Add-on 'Tvheadend:omv.local:9982' returned an error: the command failed
ERROR: GetTimers: PVR client 'Tvheadend:omv.local:9982' returned an error: the command failed
```
But I am not sure if they actually cause the freeze or if they are just a symptom of the freeze.

I have this issue since years on the Raspberry Pi, but never encountered them on more capable hardware like my Ubuntu laptop. I have the feeling that this is some kind of race condition that is more likely triggered on slower single-core systems. If I restart the Pi a sufficient amount of times, it will successfully read all the metadata and let me access live TV streams.

Any ideas how I can further debug this issue, e.g. which "server error" is produced and which "command failed"?

Full logs:
`kodi.log`: https://pastebin.com/raw/zts4gHtA
`kodi_crash.log` (triggered by `-SIGSEGV`): https://pastebin.com/raw/VHhT3d7v

### PR DESCRIPTION
**Pull request by ksooo**
Fix deadlock while reconnecting to backend after a backend response timeout (Fixes #465). Second try....

Cause of the UI freeze is a deadlock in pvr.hts, which is fixed by this PR.

Thread 27

* has tvh mtx -> CTvheadend::Process()
* wants connection mtx -> HTSPConnection::GetProtocol()

Thread 35

* has connection mtx -> HTSPConnection::Register()
* wants tvh mtx -> CTvheadend::Connected()

```log
Thread 27 (Thread 0x64050380 (LWP 320)):
#0  __lll_lock_wait (futex=0x72e66390, private=0) at lowlevellock.c:43
#1  0x76eaadcc in __GI___pthread_mutex_lock (mutex=0x72e66390) at pthread_mutex_lock.c:115
#2  0x76d8c534 in P8PLATFORM::CMutex::Lock() () from /usr/lib/libcec.so.4
#3  0x683426dc in tvheadend::HTSPConnection::GetProtocol() const () from /storage/.kodi/addons/pvr.hts/pvr.hts.so.4.4.21
#4  0x68337508 in CTvheadend::ParseEvent(htsmsg*, bool, tvheadend::entity::Event&) () from /storage/.kodi/addons/pvr.hts/pvr.hts.so.4.4.21
#5  0x683382f0 in CTvheadend::ParseEventAddOrUpdate(htsmsg*, bool) () from /storage/.kodi/addons/pvr.hts/pvr.hts.so.4.4.21
#6  0x6833c028 in CTvheadend::Process() () from /storage/.kodi/addons/pvr.hts/pvr.hts.so.4.4.21
#7  0x76d8c6e8 in P8PLATFORM::CThread::ThreadHandler(void*) () from /usr/lib/libcec.so.4
#8  0x76ea83cc in start_thread (arg=0x64050380) at pthread_create.c:486
#9  0x74da48d8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /usr/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 35 (Thread 0x5fbfb380 (LWP 331)):
#0  __lll_lock_wait (futex=0x72e693c0, private=0) at lowlevellock.c:46
#1  0x76eaadcc in __GI___pthread_mutex_lock (mutex=0x72e693c0) at pthread_mutex_lock.c:115
#2  0x76d8c534 in P8PLATFORM::CMutex::Lock() () from /usr/lib/libcec.so.4
#3  0x683353a4 in CTvheadend::Connected() () from /storage/.kodi/addons/pvr.hts/pvr.hts.so.4.4.21
#4  0x68343f48 in tvheadend::HTSPConnection::Register() () from /storage/.kodi/addons/pvr.hts/pvr.hts.so.4.4.21
#5  0x68344bd0 in tvheadend::HTSPConnection::HTSPRegister::Process() () from /storage/.kodi/addons/pvr.hts/pvr.hts.so.4.4.21
#6  0x76d8c6e8 in P8PLATFORM::CThread::ThreadHandler(void*) () from /usr/lib/libcec.so.4
#7  0x76ea83cc in start_thread (arg=0x5fbfb380) at pthread_create.c:486
#8  0x74da48d8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /usr/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

### CODE REVIEW

**Comment by ksooo** [comment]
Do not merge - PR is still WIP...

**Comment by Jalle19** [comment]
IIRC we tried to sort this connection lock mess out years ago but ended up leaving it alone.

**Comment by ksooo** [comment]
> IIRC we tried to sort this connection lock mess out years ago but ended up leaving it alone.

 @Jalle19 meanwhile I have a pretty good understanding how it all works, and yes the code is ugly, but it follows a strict logic wrt when to lock the conn mutex and I think it is implemented correctly.

File: src/tvheadend/HTSPDemuxer.cpp [hunk 1]
```diff
@@ -164,36 +165,67 @@ void HTSPDemuxer::Abort()
   ResetStatus();
 }
 
+namespace tvheadend
+{
+
+class SubScriptionSeekTime
```
Comment (Jalle19) [inline src/tvheadend/HTSPDemuxer.cpp]: Nitpick, but Subscription is just one word so the second "s" should not be capitalized

Comment (ksooo) [reply src/tvheadend/HTSPDemuxer.cpp]: Sure. Just a typo. Thanks.

**Comment by ksooo** [comment]
@christianrauch could you give this a go? I think I now found the right fix for the UI freeze.

**Comment by christianrauch** [comment]
> @christianrauch could you give this a go? I think I now found the right fix for the UI freeze.

I tried to compile it with my stable LibreELEC version that uses Kodi 18.8. I think the plugin is using new API. At least I am getting ` fatal error: kodi/addon-instance/pvr/Channels.h: No such file or directory`.

At the moment, I cannot test this. I will try to get a development version of LibreELEC running so that I can try this PR. Otherwise, are there any plans to backport this to Kodi 18?

**Comment by ksooo** [comment]
> Otherwise, are there any plans to backport this to Kodi 18?

No, no more fixes for Kodi 18, sorry.

**Comment by CvH** [comment]
https://github.com/kodi-pvr/pvr.hts/pull/469/commits/41830a4ce14695b07ac368660358b7e243303471 might fix https://github.com/kodi-pvr/pvr.hts/issues/235 too ?

**Comment by hansbogert** [comment]
could this be backported to Leia? Never hit this until I started suspending my libreelec install, but since doing that I constantly hit this and it's driving the Mrs. quite mad.

**Comment by ksooo** [comment]
Sorry, no more backports. Kodi 19 is nearing beta state.

**Comment by hansbogert** [comment]
Thanks for responding, I'll revert to leaving the media center on
continuously for now.

/update
Doh! only now I see that in this very thread someone already asked for this, sorry!
